# DataSource
spring:
  datasource:
    url: jdbc:mariadb://mariadb.S.ap-northeast-2.rds.amazonaws.com/mall
    username: root
    password: S
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MariaDB103Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  hikari:
    data-source-properties:
      useUnicode: true
      characterEncoding: UTF-8
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
